### ISSUE TITLE
502 Bad Gateway when run as service

### ISSUE THREAD

**Issue by ewingson** [CommunitySolidServer/Recipes#15]
what I did:
```
cd /tmp/recipes
git clone https://github.com/CommunitySolidServer/Recipes.git
cd Recipes/mashlib
npm ci --production
```
when run manually, the wrong server started. therefor I did one step: create the service.
```
[Unit]
Description=Solid - Social Linked Data
Documentation=https://github.com/solid/community-server
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/var/www/solidweb.me
ExecStart=/usr/bin/npx community-solid-server -c @css:config/config-mashlib.json -f /var/www/solidweb.me -b https://solidweb.me/ -p 3000
Restart=on-failure

[Install]
WantedBy=multi-user.target
```
what I got
```
# systemctl status -l communityss.service
● communityss.service - Solid - Social Linked Data
   Loaded: loaded (/lib/systemd/system/communityss.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2022-04-11 18:22:35 CEST; 2s ago
     Docs: https://github.com/solid/community-server
 Main PID: 4992 (node)
    Tasks: 11 (limit: 450)
   Memory: 154.8M
   CGroup: /system.slice/communityss.service
           └─4992 node /usr/bin/npx community-solid-server -c @css:config/config-mashlib.json -f /var/www/solidweb.me -b https://solidweb.me/ -p 3000

Apr 11 18:22:35 xyz.dedicated.hosteurope.de systemd[1]: Started Solid - Social Linked Data.
Apr 11 18:22:36 xyz.dedicated.hosteurope.de npx[4992]: 2022-04-11T16:22:36.714Z [Components.js] info: Initiating component discovery from /usr/lib/node_modules/@solid/community-server/
Apr 11 18:22:37 xyz.dedicated.hosteurope.de npx[4992]: 2022-04-11T16:22:37.587Z [Components.js] info: Discovered 136 component packages within 3435 packages
Apr 11 18:22:37 xyz.dedicated.hosteurope.de npx[4992]: 2022-04-11T16:22:37.588Z [Components.js] info: Initiating component loading
```
good news: the right server started.
no obvious errors
but 502
bad practice: maybe the type is not simple
bad practice: maybe better not ran as root
but that can't be the reason for the 502
`registered components` and `loaded configs` is missing
maybe this from `/var/log/nginx/css-ssl-error.log` can highlight another aspect on this complex topic
```
2022/04/11 18:24:18 [error] 7939#7939: *1213689 connect() failed (111: Connection refused) while connecting to upstream, client: 82.83.43.52, server: solidweb.me, request: "GET / HTTP/2.0", upstream: "http://127.0.0.1:3000/", host: "solidweb.me"
```

**Comment by ewingson** [comment]
approaching step by step.
I commented out type simple and changed user to www-data.
a `systemctl status -l communityss.service` gives
```
● communityss.service - Solid - Social Linked Data
   Loaded: loaded (/lib/systemd/system/communityss.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2022-04-12 00:25:54 CEST; 4s ago
     Docs: https://github.com/solid/community-server
 Main PID: 18384 (node)
    Tasks: 11 (limit: 450)
   Memory: 193.8M
   CGroup: /system.slice/communityss.service
           └─18384 node /usr/bin/npx community-solid-server -c @css:config/config-mashlib.json -f /var/www/solidweb.me -b https://solidweb.me/ -p 3000

Apr 12 00:25:54 xyz.dedicated.hosteurope.de systemd[1]: Started Solid - Social Linked Data.
Apr 12 00:25:55 xyz.dedicated.hosteurope.de npx[18384]: 2022-04-11T22:25:55.127Z [Components.js] info: Initiating component discovery from /usr/lib/node_modules/@solid/community-server/
Apr 12 00:25:55 xyz.dedicated.hosteurope.de npx[18384]: 2022-04-11T22:25:55.973Z [Components.js] info: Discovered 136 component packages within 3435 packages
Apr 12 00:25:55 xyz.dedicated.hosteurope.de npx[18384]: 2022-04-11T22:25:55.974Z [Components.js] info: Initiating component loading
Apr 12 00:25:58 xyz.dedicated.hosteurope.de npx[18384]: 2022-04-11T22:25:58.490Z [Components.js] info: Registered 492 components
Apr 12 00:25:58 xyz.dedicated.hosteurope.de npx[18384]: 2022-04-11T22:25:58.492Z [Components.js] info: Loaded configs
Apr 12 00:25:58 xyz.dedicated.hosteurope.de npx[18384]: 2022-04-11T22:25:58.496Z [Components.js] warn: Detected remote context lookup for 'https://linkedsoftwaredependencies.org/bundles/npm/@solid/community-server-metadata-extender/^3.0.0/components/context.jsonld' in /usr/lib/node_modules/@solid/community-server/config/config-mashlib.json. This may indicate a missing or invalid dependency, or an invalid context URL.
```
which leads me to the question:
`https://linkedsoftwaredependencies.org/bundles/npm/@solid/community-server-metadata-extender/^3.0.0/components/context.jsonld` gives a 404.
should that URL exist ?

**Comment by RubenVerborgh** [comment]
> when run manually, the wrong server started.

Let's get manual working first.

```
cd /tmp/recipes
git clone https://github.com/CommunitySolidServer/Recipes.git
cd Recipes/mashlib
npm ci --production
npx community-solid-server -c config-mashlib.json
```

> should that URL exist ?

Yes (and that's a known bug), but this request should never be performed. The fact that it is, means there's something wrong with the setup.

**Comment by ewingson** [comment]
what I did

```
ln -s /tmp/recipes/Recipes/mashlib/node_modules/@solid/community-server/bin/server.js /usr/bin/community-solid-server
cd /tmp/recipes/Recipes/mashlib
npx community-solid-server -c config-mashlib.json
```
what I got
```
2022-04-13T00:28:50.266Z [Components.js] info: Initiating component discovery from /tmp/recipes/Recipes/mashlib/node_modules/@solid/community-server/
2022-04-13T00:28:50.928Z [Components.js] info: Discovered 137 component packages within 2124 packages
2022-04-13T00:28:50.929Z [Components.js] info: Initiating component loading
2022-04-13T00:28:53.693Z [Components.js] info: Registered 495 components
2022-04-13T00:28:53.695Z [Components.js] info: Loaded configs
2022-04-13T00:28:55.291Z [Components.js] error: Detected fatal error. Generated 'componentsjs-error-state.json' with more information.
Could not create the server
Cause: Unexpected token '.'
/tmp/recipes/Recipes/mashlib/node_modules/@solid/community-server-metadata-extender/dist/MetadataExtender.js:32
        if (value?.termType === 'Literal') {
                  ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/tmp/recipes/Recipes/mashlib/node_modules/@solid/community-server-metadata-extender/dist/index.js:13:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at ConstructionStrategyCommonJs.require [as req] (internal/modules/cjs/helpers.js:74:18)
    at ConstructionStrategyCommonJs.createInstance (/tmp/recipes/Recipes/mashlib/node_modules/componentsjs/lib/construction/strategy/ConstructionStrategyCommonJs.js:23:27)
    at ConfigConstructor.createInstance (/tmp/recipes/Recipes/mashlib/node_modules/componentsjs/lib/construction/ConfigConstructor.js:86:42)
```
the debug info file can be found here
https://github.com/ewingson/lib/blob/master/errors/componentsjs-error-state.json

**Comment by RubenVerborgh** [comment]
This means your Node.js version is too old. I suggest to install 16.

**Comment by ewingson** [comment]
thanx.
manual running now.
as service 502.
am searching and looking and trying to debug.

**Comment by ewingson** [comment]
my `/lib/systemd/system/communityss.service` 
```
Unit]
Description=Solid - Social Linked Data
Documentation=https://github.com/CommunitySolidServer/CommunitySolidServer
After=network.target

[Service]
#Type=simple
User=root
WorkingDirectory=/var/www/solidweb.me
ExecStart=/usr/bin/npx community-solid-server -c @css:config/config-mashlib.json -f /var/www/solidweb.me -b https://solidweb.me/
Restart=on-failure

[Install]
WantedBy=multi-user.target
```
output of `systemctl status -l communityss.service` 
```
● communityss.service - Solid - Social Linked Data
   Loaded: loaded (/lib/systemd/system/communityss.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2022-04-13 15:16:20 CEST; 232ms ago
     Docs: https://github.com/CommunitySolidServer/CommunitySolidServer
 Main PID: 3476 (npm)
    Tasks: 11 (limit: 450)
   Memory: 27.8M
   CGroup: /system.slice/communityss.service
           └─3476 npm

Apr 13 15:16:20 xyz.dedicated.hosteurope.de systemd[1]: Started Solid - Social Linked Data.
```

**Comment by RubenVerborgh** [comment]
So as per the above that would be

```
WorkingDirectory=/tmp/recipes/Recipes/mashlib
ExecStart=/usr/bin/npx community-solid-server -c config-mashlib.json -f /var/www/solidweb.me -b https://solidweb.me/
```

assuming that `/usr/bin/npx` corresponds to the Node 16 one.

**Comment by ewingson** [comment]
;-) big grin ..... fabulous fantastic thanx Ruben !
