### ISSUE TITLE
manual start works, linux system unit fails

### ISSUE THREAD

**Issue by ewingson** [CommunitySolidServer/Recipes#23]
Version: 5.0.0

a manual start of CSS 5.0.0 works perfectly like expected.
starting the server as a systemd service fails.

here my `/lib/systemd/system/server.service`

```
[Unit]
Description=Solid - Social Linked Data
Documentation=https://github.com/CommunitySolidServer/CommunitySolidServer
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/tmp/recipes/Recipes/mashlib
ExecStart=/usr/bin/npx community-solid-server -c @css:config/config-mashlib.json -f /var/www/solidweb.me -b https://solidweb.me/
#Restart=on-failure

[Install]
WantedBy=multi-user.target
```
comment this was working fine with CSS 4. 
I commented out restart cause this gives more debug info.
the working directory should be fine.
I know it should not run as root but my node setup otherwise has not sufficient rights.

seeing the process id seems to point at a npx problem.
here the output of `systemctl -l status server.service`
```
Process: 20439 ExecStart=/usr/bin/npx community-solid-server -c @css:config/config-mashlib.json -f /var/www/solidweb.me -b https://solidweb.me/ (code=exited, status=1/FAILURE)
 Main PID: 20439 (code=exited, status=1/FAILURE)
 
Aug 18 18:13:42 lvps46-163-118-221.dedicated.hosteurope.de npx[20439]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Aug 18 18:13:42 lvps46-163-118-221.dedicated.hosteurope.de npx[20439]:     at Module.load (internal/modules/cjs/loader.js:863:32)
Aug 18 18:13:42 lvps46-163-118-221.dedicated.hosteurope.de npx[20439]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
Aug 18 18:13:42 lvps46-163-118-221.dedicated.hosteurope.de npx[20439]:     at Module.require (internal/modules/cjs/loader.js:887:19)
Aug 18 18:13:42 lvps46-163-118-221.dedicated.hosteurope.de npx[20439]:     at require (internal/modules/cjs/helpers.js:74:18)
Aug 18 18:13:42 lvps46-163-118-221.dedicated.hosteurope.de npx[20439]:     at Object.<anonymous> (/tmp/recipes/Recipes/mashlib/node_modules/@solid/access-token-verifier/dist/algorithm/verifySolidAccessToken.j
Aug 18 18:13:42 lvps46-163-118-221.dedicated.hosteurope.de npx[20439]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
Aug 18 18:13:42 lvps46-163-118-221.dedicated.hosteurope.de npx[20439]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Aug 18 18:13:42 lvps46-163-118-221.dedicated.hosteurope.de systemd[1]: communityss.service: Main process exited, code=exited, status=1/FAILURE
Aug 18 18:13:42 lvps46-163-118-221.dedicated.hosteurope.de systemd[1]: communityss.service: Failed with result 'exit-code'.
```
my kindof tabula rasa solution would be install complete new, set the rights to www-data and bother about npx.
`/usr/bin/npx` links to `/root/.nvm/versions/node/v16.14.2/lib/node_modules/npm/bin/npx-cli.js`

any help highly appreciated. solidweb.me is a production system with 65 users. user data is safely backup'ed.

**Comment by RubenVerborgh** [comment]
Could we get a diff of your config from v4 to v5?

**Comment by RubenVerborgh** [comment]
But a part of the log is missing; we'd need the top line. My guess is a permissions issue; try to chmod everything such that the group of your service user has read and write access.

**Comment by RubenVerborgh** [comment]
FYI I do

```
[Service]
User=www-data
```

which is probably a tad safer 😉

**Comment by ewingson** [comment]
BIG Thanx for the prompt answer. I'll try to chmod everything. I'm a bit heat-damaged. but will try soon.

**Comment by ewingson** [comment]
the problem persists. fallback would be a fresh, clean install. doing my best. still examining.
das Problem persistiert. chmoded to `www-data:www-data`. Ich untersuche noch.

**Comment by RubenVerborgh** [comment]
Try to get the full log; the top line will tell you everything you need to know. `sudo journalctl -u server`

**Comment by ewingson** [comment]
how do I use the `-u` flag correctly (with which arguments ?)

`journalctl` without arguments gives two tables, top line respective
```
Aug 18 21:13:39 lvps46-163-118-221.dedicated.hosteurope.de solid[18323]: 2022-08-18T19:13:39.378Z so
```
and
```
Aug 18 21:13:39 lvps46-163-118-221.dedicated.hosteurope.de solid[18323]: 2022-08-18T19:13:39.378Z solid:ACL    Checking auth <https://islamf2.solidweb.org/.acl#owner> with agent <https://islamf2.solidweb.org/
```
(crunched length)

**Comment by ewingson** [comment]
chmod'ing didn't have effect. have installed node@latest via nvm. debug info (repeat)
```
root@lvps46-163-118-221:/usr/bin# systemctl -l status communityss.service
● communityss.service - Solid - Social Linked Data
   Loaded: loaded (/lib/systemd/system/communityss.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2022-08-20 01:55:03 CEST; 7s ago
     Docs: https://github.com/CommunitySolidServer/CommunitySolidServer
  Process: 28338 ExecStart=/usr/bin/npx community-solid-server -c @css:config/config-mashlib.json -f /var/www/solidweb.me -b https://solidweb.me/ (code=exited, status=1/FAILURE)
 Main PID: 28338 (code=exited, status=1/FAILURE)

Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de npx[28338]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de npx[28338]:     at Module.load (internal/modules/cjs/loader.js:863:32)
Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de npx[28338]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de npx[28338]:     at Module.require (internal/modules/cjs/loader.js:887:19)
Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de npx[28338]:     at require (internal/modules/cjs/helpers.js:74:18)
Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de npx[28338]:     at Object.<anonymous> (/tmp/recipes/Recipes/mashlib/node_modules/@solid/access-token-verifier/dist/algorithm/verifySolidAccessToken.j
Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de npx[28338]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de npx[28338]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de systemd[1]: communityss.service: Main process exited, code=exited, status=1/FAILURE
Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de systemd[1]: communityss.service: Failed with result 'exit-code'.
```
need help to keeo the service running

**Comment by ewingson** [comment]
config
```
{
  "@context": "https://linkedsoftwaredependencies.org/bundles/npm/@solid/community-server/^5.0.0/components/context.jsonld",
  "import": [
    "css:config/app/main/default.json",
    "css:config/app/init/initialize-root.json",
    "css:config/app/setup/disabled.json",
    "css:config/app/variables/default.json",
    "css:config/http/handler/default.json",
    "css:config/http/middleware/websockets.json",
    "css:config/http/server-factory/websockets.json",
    "css:config/http/static/default.json",
    "css:config/identity/access/public.json",
    "css:config/identity/email/default.json",
    "css:config/identity/handler/default.json",
    "css:config/identity/ownership/token.json",
    "css:config/identity/pod/static.json",
    "css:config/identity/registration/enabled.json",
    "css:config/ldp/authentication/dpop-bearer.json",
    "css:config/ldp/authorization/webacl.json",
    "css:config/ldp/handler/default.json",
    "css:config/ldp/metadata-parser/default.json",
    "css:config/ldp/metadata-writer/default.json",
    "css:config/ldp/modes/default.json",
    "css:config/storage/backend/pod-quota-file.json",
    "css:config/storage/key-value/resource-store.json",
    "css:config/storage/middleware/default.json",
    "css:config/util/auxiliary/acl.json",
    "css:config/util/identifiers/suffix.json",

    "css:config/util/logging/winston.json",
    "css:config/util/representation-conversion/default.json",
    "css:config/util/resource-locker/memory.json",
    "css:config/util/variables/default.json"
  ],
  "@graph": [
    {
      "comment": [
        "A filesystem-based server with Databrowser as UI.",
        "Derived from config/file-no-setup.json"
      ]
    },

    {
      "comment": "Serve Databrowser as default representation",
      "@id": "urn:solid-server:default:DefaultUiConverter",
      "@type": "ConstantConverter",
      "contentType": "text/html",
      "filePath": "./node_modules/mashlib/dist/databrowser.html",
      "options_container": true,
      "options_document": true,
      "options_minQuality": 1,
      "options_disabledMediaRanges": [
        "image/*",
        "application/pdf"
      ]
    },

    {
      "comment": "Serve Mashlib static files.",
      "@id": "urn:solid-server:default:StaticAssetHandler",
      "@type": "StaticAssetHandler",
      "assets": [
        {
          "StaticAssetHandler:_assets_key": "/mash.css",
          "StaticAssetHandler:_assets_value": "./node_modules/mashlib/dist/mash.css"
        },
        {
          "StaticAssetHandler:_assets_key": "/mashlib.min.js",
          "StaticAssetHandler:_assets_value": "./node_modules/mashlib/dist/mashlib.min.js"
        },
        {
          "StaticAssetHandler:_assets_key": "/mashlib.min.js.map",
          "StaticAssetHandler:_assets_value": "./node_modules/mashlib/dist/mashlib.min.js.map"
        }
      ]
    },

    {
      "@id": "urn:solid-server:default:QuotaStrategy",
      "PodQuotaStrategy:_limit_amount": 50000000,
      "PodQuotaStrategy:_limit_unit": "bytes"
    },
    {
      "@id": "urn:solid-server:default:SizeReporter",
      "FileSizeReporter:_ignoreFolders": [ "^/\\.internal$" ]
    }
  ]
}
```
a diff would show only the prefixes `css:`

**Comment by RubenVerborgh** [comment]
> how do I use the `-u` flag correctly (with which arguments ?)

Looks like `sudo journalctl -u communityss.service`

Or try getting a root shell and do `/usr/bin/npx community-solid-server -c @css:config/config-mashlib.json -f /var/www/solidweb.me -b https://solidweb.me/`

**Comment by ewingson** [comment]
```
root@lvps46-163-118-221:~# journalctl -u communityss.service
-- Logs begin at Fri 2022-08-19 10:49:01 CEST, end at Sat 2022-08-20 16:09:59 CEST. --
Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de systemd[1]: Started Solid - Social Linked Data.
Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de npx[28338]: /tmp/recipes/Recipes/mashlib/node_modules/@solid/access-token-verifier/dist/algorithm/parseSolidAuthorizationHeader.js:14
Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de npx[28338]:     const [match, joseHeader, jwsPayload, jwsSignature] = /^(?:DPoP|Bearer) +([\w\-~+/]+)\.([\w\-~+/]+)\.([\w\-~+/]+)(?:=+)?$/i.exec(auth
Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de npx[28338]:                                                                                                                                          
Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de npx[28338]: SyntaxError: Unexpected token '?'
Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de npx[28338]:     at wrapSafe (internal/modules/cjs/loader.js:915:16)
Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de npx[28338]:     at Module._compile (internal/modules/cjs/loader.js:963:27)
Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de npx[28338]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de npx[28338]:     at Module.load (internal/modules/cjs/loader.js:863:32)
Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de npx[28338]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de npx[28338]:     at Module.require (internal/modules/cjs/loader.js:887:19)
Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de npx[28338]:     at require (internal/modules/cjs/helpers.js:74:18)
Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de npx[28338]:     at Object.<anonymous> (/tmp/recipes/Recipes/mashlib/node_modules/@solid/access-token-verifier/dist/algorithm/verifySolidAccessToken.j
Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de npx[28338]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de npx[28338]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de systemd[1]: communityss.service: Main process exited, code=exited, status=1/FAILURE
Aug 20 01:55:03 lvps46-163-118-221.dedicated.hosteurope.de systemd[1]: communityss.service: Failed with result 'exit-code'.
```
and
```
root@lvps46-163-118-221:~# /usr/bin/npx community-solid-server -c @css:config/config-mashlib.json -f /var/www/solidweb.me -b https://solidweb.me/
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/community-solid-server - Not found
npm ERR! 404 
npm ERR! 404  'community-solid-server@latest' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-08-20T14_13_05_590Z-debug-0.log
```
can you help diagnosing further, Ruben ?

**Comment by RubenVerborgh** [comment]
> can you help diagnosing further, Ruben ?

Yes, it has nothing to do with CSS; it's the wrong Node version being started. That's why it does not recognize the syntax.

I recommend installing a more modern Node version globally on your system.

**Comment by ewingson** [comment]
okay, I' ll try node@latest and link it from /usr/bin/npx to the cli, right ?

**Comment by RubenVerborgh** [comment]
Node 16 or 19 should do; I'd just skip nvm and install it via package manager https://nodejs.org/en/download/package-manager/

**Comment by ewingson** [comment]
I had to juggle with 2 nodes cause I have NSS (solidweb.org) running on the same machine. will keep you posted.

**Comment by RubenVerborgh** [comment]
You can also `/path/to/your/node/12.34.56 npx community-solid-server` or `/path/to/your/node/12.34.56 /path/to/your/community-solid-server/bin/server.js`

**Comment by ewingson** [comment]
now have node 16
hmm why 12.34.56 ?

**Comment by ewingson** [comment]
q: have used
```
# Using Debian, as root
curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
apt-get install -y nodejs
```
where do I find the correct path ?

**Comment by ewingson** [comment]
`/usr/lib/node_modules/npm` I guess ?

**Comment by ewingson** [comment]
```
root@lvps46-163-118-221:/usr/lib/node_modules/npm/bin# ls -la
total 36
drwxr-xr-x 3 root root 4096 Aug 20 17:20 .
drwxr-xr-x 7 root root 4096 Aug 20 17:20 ..
drwxr-xr-x 2 root root 4096 Aug 20 17:20 node-gyp-bin
-rwxr-xr-x 1 root root 1365 Jul  7 13:49 npm
-rwxr-xr-x 1 root root   54 Jul  7 13:49 npm-cli.js
-rwxr-xr-x 1 root root  483 Jul  7 13:49 npm.cmd
-rwxr-xr-x 1 root root 1567 Jul  7 13:49 npx
-rwxr-xr-x 1 root root 2836 Jul  7 13:49 npx-cli.js
-rwxr-xr-x 1 root root  539 Jul  7 13:49 npx.cmd
```

**Comment by ewingson** [comment]
technical
```
root@lvps46-163-118-221:/usr/bin# /usr/bin/npx community-solid-server -c @css:config/config-mashlib.json -f /var/www/solidweb.me -b https://solidweb.me/
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/community-solid-server - Not found
npm ERR! 404 
npm ERR! 404  'community-solid-server@latest' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-08-20T16_13_17_323Z-debug-0.log
```
emotional: I need some AWK

**Comment by RubenVerborgh** [comment]
> where do I find the correct path ?

`which node`

> 'community-solid-server@latest' is not in this registry.

The package you need to install is `@solid/community-server`

**Comment by ewingson** [comment]
> > where do I find the correct path ?
> 
> `which node`

I am afraid I have messed up the node installation. `which node` still shows the nvm one (16.17.0)

> > 'community-solid-server@latest' is not in this registry.
> 
> The package you need to install is `@solid/community-server`

I have done a `git clone` and `npm ci --production` from the recipes and thought this was sufficient.

**Comment by ewingson** [comment]
the combined, gathered info in this admittedly long and disturbing thread was enough for me to have 5.0.0 with SolidOS running.

close.
